// <auto-generated />
using System;
using EmployerInfrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EmployerInfrastructure.Migrations
{
    [DbContext(typeof(EmployeeDbContext))]
    [Migration("20220514230140_initialMigration")]
    partial class initialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmployerDomain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmployeeName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            AccountNumber = "01234550",
                            CreatedUTC = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeName = "John"
                        },
                        new
                        {
                            EmployeeId = 2,
                            AccountNumber = "56264550",
                            CreatedUTC = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Local),
                            EmployeeName = "Pete"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
